drivers/input: fingerprint: focaltech: kill unused variable
../drivers/input/fingerprint/focaltech/ff_ctl.c:508:28: error: unused variable cmd_names [-Werror,-Wunused-variable]
  508 |         static const char *cmd_names[] = {
      |                            ^~~~~~~~~
1 error generated.

Signed-off-by: fukiame <fukiame@proton.me>